### ISSUE TITLE
Build Error: GitTfsPlugin does not implement IGitPlugin?

### ISSUE THREAD

**Issue by MarkDHarris** [git-tfs/git-tfs-gitextensions-plugin#16]
Is this still an active codebase?  I have tried several times to clone the repository but it reports:  ""Cloning into 'gitextensions'... fatal: reference is not a tree: 576582891c6312c3f9d354be5583059ca12cae56 Unable to checkout '576582891c6312c3f9d354be5583059ca12cae56' in submodule path 'gitextensions'""

So I gave up on that and cloned the gitextensions repository and then tried to add this code directly into the gitextensions Plugins folder and build everything together.  

This almost works.  I am at a point where I am getting a build failure on this code because the GitTfsPlugin (which inherits from IGitPlugin) does not implement IGitPlugin.  At least that's what the build error says.  I don't understand how this code would inherit from it but not implement it unless it is so old that the interface changed but that doesn't seem right either.

Anyway, to fix that build error, I had to implement that interface which adds a property "ISettingsSource IGitPlugin.Settings" and a method "public IEnumerable<ISetting> GetSettings()".

Unfortunately, I don't know enough about this code to know what these two need to implement.

Any help or suggestions?  I use GitExtensions but I would really like to be able to use git tfs directly from the GUI.

Thanks,
Mark

**Comment by roend83** [comment]
I haven't been maintaining this code for a couple years now.  I've moved on to another company that does not use TFS, so there isn't any motivation for me to keep this project up to date.  I'd be happy to hand the keys over to someone who wants to maintain this in future.

**Comment by MarkDHarris** [comment]
If I can get this to work I would certainly contribute an updated commit and consider future contributions but right now it doesn't work because of 2 build errors.  

Error	1	'GitTfs.GitExtensions.Plugin.GitTfsPlugin' does not implement interface member 'GitUIPluginInterfaces.IGitPlugin.Settings'. 'GitTfs.GitExtensions.Plugin.GitTfsPlugin.Settings' cannot implement 'GitUIPluginInterfaces.IGitPlugin.Settings' because it does not have the matching return type of 'GitUIPluginInterfaces.ISettingsSource'.	D:\gitext\gitextensions\Plugins\git-tfs-gitextensions\GitTfsPlugin.cs	10	18	GitTfs.GitExtensions

Error	2	'GitTfs.GitExtensions.Plugin.GitTfsPlugin' does not implement interface member 'GitUIPluginInterfaces.IGitPlugin.GetSettings()'	D:\gitext\gitextensions\Plugins\git-tfs-gitextensions\GitTfsPlugin.cs	10	18	GitTfs.GitExtensions


I am not familiar enough with this code or gitextension plugin design.  Are there any docs you can point me to?

**Comment by pmiossec** [comment]
Should be fixed,  now...

**Comment by pmiossec** [comment]
See https://github.com/git-tfs/git-tfs-gitextensions-plugin/releases

**Comment by MarkDHarris** [comment]
Thank you pmiossec!  (For both pointing me to the "script" method as well as fixing this plugin.)

**Comment by pmiossec** [comment]
No problem. I understand that it is sometimes difficult to contribute to a project....
And I even see that's an improvement in GitExtensions that I made that partly break the plugin ;)

Is it fixed? Could we close the issue?

**Comment by MarkDHarris** [comment]
Yes, I was able to successfully clone, build, and run GitExt with the Git-Tfs Plugin.  I think the issue is successfully resolved. Thanks again.
